    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
 level.layers["DynamicWorld"].objects["object0"] = WorldSet.newBox({x=1170,y=954})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object0"].image)
 level.layers["DynamicWorld"].objects["object1"] = WorldSet.newCompanionCube({x=534,y=510})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newFloor({x=524,y=1072})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["StaticWorld"].objects["object3"] = WorldSet.newpar_floor({x=1282,y=278})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object3"].image)
 level.layers["StaticWorld"].objects["object4"] = WorldSet.newhor_floor({x=1852,y=332})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object4"].image)
 level.layers["StaticWorld"].objects["object5"] = WorldSet.newleftTop_floor({x=1544,y=1258})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object5"].image)
 level.layers["StaticWorld"].objects["object6"] = WorldSet.newThorn({x=1424,y=288})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object6"].image)
 level.layers["InteractiveWorld"].objects["object7"] = WorldSet.newSpinningCog({x=600,y=-20})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object7"].image)
 level.layers["InteractiveWorld"].objects["object8"] = WorldSet.newWoodenDoor({x=186,y=188})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object8"].image)
 level.layers["InteractiveWorld"].objects["object9"] = WorldSet.newFireBall({x=968,y=564})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object9"].image)
 level.layers["DynamicWorld"].objects["object10"] = WorldSet.newBox({x=1524,y=844})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object10"].image)
 level.layers["StaticWorld"].objects["object11"] = WorldSet.newFloor({x=2098,y=560})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object11"].image)
 level.layers["StaticWorld"].objects["object12"] = WorldSet.newpar_floor({x=1916,y=1118})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object12"].image)
 level.layers["DynamicWorld"].objects["object13"] = WorldSet.newCompanionCube({x=4002,y=668})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object13"].image)
 level.layers["DynamicWorld"].objects["object14"] = WorldSet.newBox({x=4198,y=404})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object14"].image)
 level.layers["StaticWorld"].objects["object15"] = WorldSet.newleftTop_floor({x=3934,y=1110})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object15"].image)
 level.layers["StaticWorld"].objects["object16"] = WorldSet.newThorn({x=3426,y=516})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object16"].image)
 level.layers["StaticWorld"].objects["object17"] = WorldSet.newpar_floor({x=3516,y=196})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object17"].image)
 level.layers["StaticWorld"].objects["object18"] = WorldSet.newleftTop_floor({x=3990,y=258})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object18"].image)
 level.layers["InteractiveWorld"].objects["object19"] = WorldSet.newSpinningCog({x=3474,y=1192})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object19"].image)
 level.layers["StaticWorld"].objects["object20"] = WorldSet.newleftTop_floor({x=3400,y=908})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object20"].image)
 level.layers["InteractiveWorld"].objects["object21"] = WorldSet.newWoodenDoor({x=3088,y=728})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object21"].image)
 level.layers["StaticWorld"].objects["object22"] = WorldSet.newThorn({x=3876,y=500})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object22"].image)
 level.layers["StaticWorld"].objects["object23"] = WorldSet.newpar_floor({x=3142,y=198})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object23"].image)
 level.layers["InteractiveWorld"].objects["object24"] = WorldSet.newFireBall({x=3096,y=1220})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object24"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    return level

end -- CreateLevel