    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
 level.layers["StaticWorld"].objects["object0"] = WorldSet.newhor_floor({x=10,y=300})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object0"].image)
 level.layers["StaticWorld"].objects["object0"].image:rotate(270)
 level.layers["StaticWorld"].objects["object1"] = WorldSet.newhor_floor({x=10,y=900})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object1"].image:rotate(270)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newhor_floor({x=10,y=2100})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["StaticWorld"].objects["object2"].image:rotate(270)
 level.layers["StaticWorld"].objects["object3"] = WorldSet.newhor_floor({x=10,y=1500})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object3"].image)
 level.layers["StaticWorld"].objects["object3"].image:rotate(270)
 level.layers["StaticWorld"].objects["object4"] = WorldSet.newhor_floor({x=300,y=2390})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object4"].image)
 level.layers["StaticWorld"].objects["object5"] = WorldSet.newhor_floor({x=844,y=2238})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object5"].image)
 level.layers["StaticWorld"].objects["object5"].image:rotate(330)
 level.layers["StaticWorld"].objects["object6"] = WorldSet.newhor_floor({x=1304,y=1888})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object6"].image)
 level.layers["StaticWorld"].objects["object6"].image:rotate(315)
 level.layers["StaticWorld"].objects["object7"] = WorldSet.newhor_floor({x=1656,y=1432})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object7"].image)
 level.layers["StaticWorld"].objects["object7"].image:rotate(300)
 level.layers["StaticWorld"].objects["object8"] = WorldSet.newThorn({x=1610,y=1360})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object8"].image)
 level.layers["StaticWorld"].objects["object8"].image:rotate(300)
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newThorn({x=1240,y=1848})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object9"].image:rotate(315)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newThorn({x=816,y=2166})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["StaticWorld"].objects["object10"].image:rotate(330)
 level.layers["StaticWorld"].objects["object11"] = WorldSet.newhor_floor({x=1810,y=880})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object11"].image)
 level.layers["StaticWorld"].objects["object11"].image:rotate(270)
 level.layers["StaticWorld"].objects["object12"] = WorldSet.newhor_floor({x=2262,y=880})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object12"].image)
 level.layers["StaticWorld"].objects["object12"].image:rotate(270)
 level.layers["InteractiveWorld"].objects["object13"] = WorldSet.newSpinningTire({x=2050,y=1768})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object13"].image)
 level.layers["StaticWorld"].objects["object14"] = WorldSet.newhor_floor({x=2262,y=284})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object14"].image)
 level.layers["StaticWorld"].objects["object14"].image:rotate(270)
 level.layers["StaticWorld"].objects["object15"] = WorldSet.newhor_floor({x=1960,y=10})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object15"].image)
 level.layers["StaticWorld"].objects["object16"] = WorldSet.newhor_floor({x=1360,y=10})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object16"].image)
 level.layers["StaticWorld"].objects["object17"] = WorldSet.newhor_floor({x=760,y=10})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object17"].image)
 level.layers["StaticWorld"].objects["object18"] = WorldSet.newhor_floor({x=320,y=10})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object18"].image)
 level.layers["StaticWorld"].objects["object19"] = WorldSet.newhor_floor({x=2410,y=1428})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object19"].image)
 level.layers["StaticWorld"].objects["object19"].image:rotate(60)
 level.layers["InteractiveWorld"].objects["object20"] = WorldSet.newfloatingFloor({x=1560,y=2090})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object20"].image)
 level.layers["InteractiveWorld"].objects["object21"] = WorldSet.newfloatingFloor({x=1760,y=2090})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object21"].image)
 level.layers["StaticWorld"].objects["object22"] = WorldSet.newhor_floor({x=2410,y=1940})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object22"].image)
 level.layers["StaticWorld"].objects["object22"].image:rotate(300)
 level.layers["StaticWorld"].objects["object23"] = WorldSet.newhor_floor({x=2058,y=2404})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object23"].image)
 level.layers["StaticWorld"].objects["object23"].image:rotate(315)
 level.layers["StaticWorld"].objects["object24"] = WorldSet.newhor_floor({x=1594,y=2764})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object24"].image)
 level.layers["StaticWorld"].objects["object24"].image:rotate(330)
 level.layers["StaticWorld"].objects["object25"] = WorldSet.newhor_floor({x=1040,y=2914})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object25"].image)
 level.layers["StaticWorld"].objects["object26"] = WorldSet.newhor_floor({x=448,y=2914})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object26"].image)
 level.layers["StaticWorld"].objects["object27"] = WorldSet.newhor_floor({x=146,y=2684})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object27"].image)
 level.layers["StaticWorld"].objects["object27"].image:rotate(90)
 level.layers["InteractiveWorld"].objects["object28"] = WorldSet.newfloatingFloor({x=1940,y=2090})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object28"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    return level

end -- CreateLevel