    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
 level.layers["StaticWorld"].objects["object0"] = WorldSet.newpar_floor({x=10,y=150})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object0"].image)
 level.layers["StaticWorld"].objects["object1"] = WorldSet.newpar_floor({x=10,y=450})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newpar_floor({x=10,y=750})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["StaticWorld"].objects["object3"] = WorldSet.newhor_floor({x=300,y=890})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object3"].image)
 level.layers["StaticWorld"].objects["object4"] = WorldSet.newhor_floor({x=798,y=1098})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object4"].image)
 level.layers["StaticWorld"].objects["object4"].image:rotate(45)
 level.layers["StaticWorld"].objects["object5"] = WorldSet.newhor_floor({x=1264,y=1458})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object5"].image)
 level.layers["StaticWorld"].objects["object5"].image:rotate(30)
 level.layers["StaticWorld"].objects["object6"] = WorldSet.newhor_floor({x=1820,y=1610})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object6"].image)
 level.layers["StaticWorld"].objects["object7"] = WorldSet.newhor_floor({x=2258,y=1344})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object7"].image)
 level.layers["StaticWorld"].objects["object7"].image:rotate(300)
 level.layers["StaticWorld"].objects["object8"] = WorldSet.newhor_floor({x=2614,y=878})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object8"].image)
 level.layers["StaticWorld"].objects["object8"].image:rotate(315)
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newhor_floor({x=3076,y=520})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object9"].image:rotate(330)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newhor_floor({x=3630,y=374})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["Monster"].objects["object11"] = EnemySet.newMonsterCannon({x=3020,y=480})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object11"].image)
 level.layers["Monster"].objects["object11"].image:rotate(330)
 level.layers["Monster"].objects["object12"] = EnemySet.newMonsterCannon({x=2608,y=800})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object12"].image)
 level.layers["Monster"].objects["object12"].image:rotate(315)
 level.layers["StaticWorld"].objects["object13"] = WorldSet.newThorn({x=2206,y=1286})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object13"].image)
 level.layers["StaticWorld"].objects["object13"].image:rotate(300)
 level.layers["StaticWorld"].objects["object14"] = WorldSet.newThorn({x=2698,y=692})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object14"].image)
 level.layers["StaticWorld"].objects["object14"].image:rotate(315)
 level.layers["DynamicWorld"].objects["object15"] = WorldSet.newBox({x=2278,y=1198})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object15"].image)
 level.layers["DynamicWorld"].objects["object15"].image:rotate(300)
 level.layers["Monster"].objects["object16"] = EnemySet.newMonsterCannon({x=1946,y=1546})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object16"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    return level

end -- CreateLevel