    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
level.layers["Image"] = display.newGroup()
level.layers["Image"].name = "Image"
level.layers["Image"].objects = {}
 level.layers["Image"].objects["object0"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",822,438)
 level.layers["Image"]:insert(level.layers["Image"].objects["object0"])
 level.layers["Image"].objects["object1"] = display.newImage("kalacool/sango/image/character/coodog.png",536,552)
 level.layers["Image"]:insert(level.layers["Image"].objects["object1"])
 level.layers["Image"].objects["object1"]:rotate(315)
 level.layers["Image"].objects["object2"] = display.newImage("kalacool/sango/image/character/coodog.png",982,368)
 level.layers["Image"]:insert(level.layers["Image"].objects["object2"])
 level.layers["Image"].objects["object3"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",650,248)
 level.layers["Image"]:insert(level.layers["Image"].objects["object3"])
 level.layers["Image"].objects["object4"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",930,158)
 level.layers["Image"]:insert(level.layers["Image"].objects["object4"])
 level.layers["Image"].objects["object5"] = display.newImage("kalacool/sango/image/character/coodog.png",1132,468)
 level.layers["Image"]:insert(level.layers["Image"].objects["object5"])
 level.layers["Image"].objects["object5"]:rotate(45)
 level.layers["Image"].objects["object6"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",874,548)
 level.layers["Image"]:insert(level.layers["Image"].objects["object6"])
 level.layers["Image"].objects["object7"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",652,456)
 level.layers["Image"]:insert(level.layers["Image"].objects["object7"])
 level.layers["Image"].objects["object8"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",1040,580)
 level.layers["Image"]:insert(level.layers["Image"].objects["object8"])
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newhor_floor({x=276,y=714})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newhor_floor({x=876,y=714})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["Image"].objects["object11"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1040,706)
 level.layers["Image"]:insert(level.layers["Image"].objects["object11"])
 level.layers["StaticWorld"].objects["object12"] = WorldSet.newhor_floor({x=1478,y=710})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object12"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    level:insert(level.layers["Image"])

    return level

end -- CreateLevel