    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.SupplementSet")
require("kalacool.sango.Set.MechanismSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "testversion182"

local MonsterSpawnWavesClass = require "kalacool.sango.System.MonsterSpawnWaves"
MonsterImageGroup = display.newGroup()
MonsterSpawnWavesClass.NextWaveHandler(MonsterImageGroup)
level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
level.layers["Image"] = display.newGroup()
level.layers["Image"].name = "Image"
level.layers["Image"].objects = {}
MonsterSpawnWavesClass.addMonster({ID=98,x=1736,y=764,wave=2,xL=5000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=98,x=1482,y=910,wave=2,xL=5000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=98,x=1422,y=1272,wave=2,xL=5000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=98,x=1424,y=526,wave=2,xL=5000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=946,y=726,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=1010,y=464,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=806,y=638,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=666,y=710,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=786,y=876,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=946,y=840,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=1108,y=716,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=1038,y=626,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=900,y=652,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=868,y=770,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=808,y=752,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=806,y=540,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=742,y=516,wave=1,xL=1000,xR=2000})
MonsterSpawnWavesClass.addMonster({ID=1,x=952,y=568,wave=1,xL=1000,xR=2000})
 level.layers["Image"].objects["object18"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1784,340)
 level.layers["Image"]:insert(level.layers["Image"].objects["object18"])
 level.layers["Image"].objects["object19"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1662,336)
 level.layers["Image"]:insert(level.layers["Image"].objects["object19"])
 level.layers["Image"].objects["object20"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1150,252)
 level.layers["Image"]:insert(level.layers["Image"].objects["object20"])
 level.layers["Image"].objects["object21"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",790,278)
 level.layers["Image"]:insert(level.layers["Image"].objects["object21"])
 level.layers["Image"].objects["object22"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",510,444)
 level.layers["Image"]:insert(level.layers["Image"].objects["object22"])
 level.layers["Image"].objects["object23"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",278,882)
 level.layers["Image"]:insert(level.layers["Image"].objects["object23"])
 level.layers["Image"].objects["object24"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",592,1086)
 level.layers["Image"]:insert(level.layers["Image"].objects["object24"])
 level.layers["Image"].objects["object25"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",806,1160)
 level.layers["Image"]:insert(level.layers["Image"].objects["object25"])
 level.layers["Image"].objects["object26"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",948,1174)
 level.layers["Image"]:insert(level.layers["Image"].objects["object26"])
 level.layers["Image"].objects["object27"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1104,1138)
 level.layers["Image"]:insert(level.layers["Image"].objects["object27"])
 level.layers["Image"].objects["object28"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1212,1048)
 level.layers["Image"]:insert(level.layers["Image"].objects["object28"])
 level.layers["Supplement"].objects["object29"] = SupplementSet.newDogFood({x=2068,y=516})
 level.layers["Supplement"]:insert(level.layers["Supplement"].objects["object29"].image)
 level.layers["Supplement"].objects["object30"] = SupplementSet.newDogFood({x=1868,y=536})
 level.layers["Supplement"]:insert(level.layers["Supplement"].objects["object30"].image)
 level.layers["Supplement"].objects["object31"] = SupplementSet.newDogFood({x=1758,y=524})
 level.layers["Supplement"]:insert(level.layers["Supplement"].objects["object31"].image)
 level.layers["StaticWorld"].objects["boundTop"] = WorldSet.newboundRecRow({x=2700,y=-120})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundTop"].image)
 level.layers["StaticWorld"].objects["boundDown"] = WorldSet.newboundRecRow({x=2700,y=3030})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundDown"].image)
 level.layers["StaticWorld"].objects["boundLeft"] = WorldSet.newboundRecCol({x=-700,y=1500})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundLeft"].image) level.layers["StaticWorld"].objects["boundRight"] = WorldSet.newboundRecCol({x=6100,y=1500}) level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundRight"].image)scene:dispatchEvent({name='nextWave',nextWave = 1})
    level:insert(MonsterImageGroup)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    level:insert(level.layers["Image"])

    return level

end -- CreateLevel