    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
 level.layers["Image"].objects["object0"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1482,908)
 level.layers["Image"]:insert(level.layers["Image"].objects["object0"])
 level.layers["Image"].objects["object1"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1058,834)
 level.layers["Image"]:insert(level.layers["Image"].objects["object1"])
 level.layers["Image"].objects["object1"]:rotate(315)
 level.layers["Image"].objects["object2"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1362,384)
 level.layers["Image"]:insert(level.layers["Image"].objects["object2"])
 level.layers["Image"].objects["object2"]:rotate(60)
 level.layers["Image"].objects["object3"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1748,524)
 level.layers["Image"]:insert(level.layers["Image"].objects["object3"])
 level.layers["Image"].objects["object4"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1430,730)
 level.layers["Image"]:insert(level.layers["Image"].objects["object4"])
 level.layers["Image"].objects["object4"]:rotate(330)
 level.layers["StaticWorld"].objects["object5"] = WorldSet.newhor_floor({x=396,y=1060})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object5"].image)
 level.layers["StaticWorld"].objects["object6"] = WorldSet.newhor_floor({x=1152,y=1074})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object6"].image)
 level.layers["StaticWorld"].objects["object7"] = WorldSet.newhor_floor({x=1812,y=1076})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object7"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    return level

end -- CreateLevel