    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
 level.layers["StaticWorld"].objects["object0"] = WorldSet.newpar_floor({x=106,y=604})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object0"].image)
 level.layers["StaticWorld"].objects["object0"].image:rotate(315)
 level.layers["StaticWorld"].objects["object1"] = WorldSet.newpar_floor({x=350,y=710})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object1"].image:rotate(270)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newpar_floor({x=596,y=810})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["StaticWorld"].objects["object2"].image:rotate(315)
 level.layers["StaticWorld"].objects["object3"] = WorldSet.newpar_floor({x=796,y=1010})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object3"].image)
 level.layers["StaticWorld"].objects["object3"].image:rotate(315)
 level.layers["StaticWorld"].objects["object4"] = WorldSet.newpar_floor({x=1042,y=1114})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object4"].image)
 level.layers["StaticWorld"].objects["object4"].image:rotate(270)
 level.layers["StaticWorld"].objects["object5"] = WorldSet.newhor_floor({x=1444,y=1258})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object5"].image)
 level.layers["StaticWorld"].objects["object5"].image:rotate(30)
 level.layers["StaticWorld"].objects["object6"] = WorldSet.newhor_floor({x=1958,y=1554})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object6"].image)
 level.layers["StaticWorld"].objects["object6"].image:rotate(30)
 level.layers["StaticWorld"].objects["object7"] = WorldSet.newThorn({x=1424,y=1158})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object7"].image)
 level.layers["StaticWorld"].objects["object7"].image:rotate(30)
 level.layers["StaticWorld"].objects["object8"] = WorldSet.newThorn({x=1576,y=1246})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object8"].image)
 level.layers["StaticWorld"].objects["object8"].image:rotate(30)
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newThorn({x=414,y=790})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object9"].image:rotate(180)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newThorn({x=638,y=960})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["StaticWorld"].objects["object10"].image:rotate(225)
 level.layers["StaticWorld"].objects["object11"] = WorldSet.newThorn({x=788,y=894})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object11"].image)
 level.layers["StaticWorld"].objects["object11"].image:rotate(45)
 level.layers["StaticWorld"].objects["object12"] = WorldSet.newpar_floor({x=8,y=350})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object12"].image)
 level.layers["StaticWorld"].objects["object13"] = WorldSet.newpar_floor({x=8,y=148})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object13"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    return level

end -- CreateLevel