    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.SupplementSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

local MonsterSpawnWavesClass = require "kalacool.sango.System.MonsterSpawnWaves"
MonsterImageGroup = display.newGroup()
MonsterSpawnWavesClass.NextWaveHandler(MonsterImageGroup)
level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
level.layers["Image"] = display.newGroup()
level.layers["Image"].name = "Image"
level.layers["Image"].objects = {}
 level.layers["Image"].objects["object0"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1538,560)
 level.layers["Image"]:insert(level.layers["Image"].objects["object0"])
 level.layers["Image"].objects["object1"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1100,708)
 level.layers["Image"]:insert(level.layers["Image"].objects["object1"])
 level.layers["Image"].objects["object2"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",980,1100)
 level.layers["Image"]:insert(level.layers["Image"].objects["object2"])
 level.layers["Image"].objects["object3"] = display.newImage("kalacool/sango/image/world/dynamicWorld/box.png",1520,1172)
 level.layers["Image"]:insert(level.layers["Image"].objects["object3"])
 level.layers["Image"].objects["object4"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",1690,988)
 level.layers["Image"]:insert(level.layers["Image"].objects["object4"])
 level.layers["Image"].objects["object5"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",1266,1158)
 level.layers["Image"]:insert(level.layers["Image"].objects["object5"])
 level.layers["Image"].objects["object6"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",1406,900)
 level.layers["Image"]:insert(level.layers["Image"].objects["object6"])
 level.layers["Image"].objects["object7"] = display.newImage("kalacool/sango/image/world/dynamicWorld/companionCube.png",1678,722)
 level.layers["Image"]:insert(level.layers["Image"].objects["object7"])
 level.layers["StaticWorld"].objects["object8"] = WorldSet.newCheckDoor({x=2058,y=402})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object8"].image)
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newCheckDoor({x=1212,y=370})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newCheckDoor({x=970,y=480})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["StaticWorld"].objects["object11"] = WorldSet.newCheckDoor({x=550,y=684})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object11"].image)
MonsterSpawnWavesClass.addMonster({ID=3,x=1956,y=838,wave=1})
MonsterSpawnWavesClass.addMonster({ID=3,x=1850,y=680,wave=3})
MonsterSpawnWavesClass.addMonster({ID=3,x=1756,y=306,wave=2})
MonsterSpawnWavesClass.addMonster({ID=3,x=1646,y=216,wave=1})
MonsterSpawnWavesClass.addMonster({ID=2,x=2108,y=798,wave=2})
 level.layers["StaticWorld"].objects["boundTop"] = WorldSet.newboundRecRow({x=2700,y=-120})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundTop"].image)
 level.layers["StaticWorld"].objects["boundDown"] = WorldSet.newboundRecRow({x=2700,y=3030})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundDown"].image)
 level.layers["StaticWorld"].objects["boundLeft"] = WorldSet.newboundRecCol({x=-700,y=1500})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundLeft"].image) level.layers["StaticWorld"].objects["boundRight"] = WorldSet.newboundRecCol({x=6100,y=1500}) level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["boundRight"].image)scene:dispatchEvent({name='nextWave',nextWave = 1})
    level:insert(MonsterImageGroup)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    level:insert(level.layers["Image"])

    return level

end -- CreateLevel