    -- Generated by Kalacool Editor

--this String is only for test

	--you should add your own string
--the string will be generated before the class module string
	--test
 level.layers["DynamicWorld"].objects["object0"] = WorldSet.newCompanionCube({x=1476,y=584})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object0"].image)
 level.layers["DynamicWorld"].objects["object1"] = WorldSet.newCompanionCube({x=924,y=532})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object1"].image)
 level.layers["DynamicWorld"].objects["object2"] = WorldSet.newCompanionCube({x=754,y=782})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object2"].image)
 level.layers["DynamicWorld"].objects["object3"] = WorldSet.newCompanionCube({x=1222,y=740})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object3"].image)
--this String is only for test

	--you should add your own string
--the string will be generated after the class module string
	--test
