    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
 level.layers["Monster"].objects["object0"] = EnemySet.newMonsterCannon({x=1334,y=562})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object0"].image)
 level.layers["InteractiveWorld"].objects["object1"] = WorldSet.newSpinningTire({x=1468,y=1352})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newThorn({x=2006,y=782})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["StaticWorld"].objects["object3"] = WorldSet.newpar_floor({x=1896,y=468,testset=dd})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object3"].image)
 level.layers["Monster"].objects["object4"] = EnemySet.newMonsterFireball({x=850,y=962,xL=42})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object4"].image)
 level.layers["Monster"].objects["object5"] = EnemySet.newMonsterFireball({x=2020,y=1256,xR=20})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object5"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    return level

end -- CreateLevel